[tool.poetry]
name = "magneticTweezers"
version = "0.1.0"
description = ""
authors = ["Erik Plesko <erik.plesko@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pyserial = "^3.5"
numpy = "^1.19"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
notebook = "^7"
matplotlib = "^3.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
